# Generated by Django 5.2.7 on 2025-11-04 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_num', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Couriers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
            options={
                'db_table': 'Couriers',
            },
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Offices',
            },
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='mainapp.clients')),
                ('from_office', models.ForeignKey(db_column='from_office_id', on_delete=django.db.models.deletion.CASCADE, related_name='from_shipments', to='mainapp.offices')),
                ('to_office', models.ForeignKey(db_column='to_office_id', on_delete=django.db.models.deletion.CASCADE, related_name='to_shipments', to='mainapp.offices')),
            ],
            options={
                'db_table': 'Shipments',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(db_column='shipment_id', on_delete=django.db.models.deletion.CASCADE, to='mainapp.shipments')),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipment', models.ForeignKey(db_column='shipment_id', on_delete=django.db.models.deletion.CASCADE, to='mainapp.shipments')),
            ],
            options={
                'db_table': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Scheduled', max_length=50)),
                ('courier', models.ForeignKey(blank=True, db_column='courier_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.couriers')),
                ('shipment', models.OneToOneField(db_column='shipment_id', on_delete=django.db.models.deletion.CASCADE, to='mainapp.shipments')),
            ],
            options={
                'db_table': 'Delivery',
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(db_column='shipment_id', on_delete=django.db.models.deletion.CASCADE, to='mainapp.shipments')),
            ],
            options={
                'db_table': 'Tracking',
            },
        ),
    ]
