# Generated by Django 5.2.7 on 2025-11-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.EmailField(default='temp@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='phone',
            field=models.CharField(default='0990260433', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='clients',
            table=None,
        ),
    ]
